# themes from https://github.com/alacritty/alacritty-theme

import = [
    "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
]

[font]
size = 12

[font.normal]
family = "ComicCodeLigatures Nerd Font"

[window]
opacity=0.99
decorations = "none"

[window.padding]
x = 7
y = 0

[shell]
program = "/opt/homebrew/bin/tmux"

[env]
term = "tmux-265color"
