[font]
size = 17

[font.normal]
family = "ComicCodeLigatures Nerd Font"

[window]
opacity=0.95
decorations = "none"

[window.padding]
x = 7
y = 0

[env]
term = "tmux-256color"

[general]
# themes from https://github.com/alacritty/alacritty-theme

import = [
    "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]

# [shell]
# program = "/opt/homebrew/bin/tmux"
