# themes from https://github.com/alacritty/alacritty-theme

import = [
    "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
]

[font]
size = 15

[font.normal]
family = "ComicCodeLigatures Nerd Font"

[window]
opacity=0.95
decorations = "none"

[window.padding]
x = 7
y = 0

[env]
term = "tmux-256color"

# [shell]
# program = "/opt/homebrew/bin/tmux"
