[font]
size = 16

[font.normal]
# family = "ZedMono Nerd Font Propo"
family = "JetBrainsMonoNL Nerd Font Propo"

[window]
opacity=0.95
decorations = "none"

[window.padding]
x = 7
y = 0

[env]
term = "tmux-256color"

[general]
# themes from https://github.com/alacritty/alacritty-theme

import = [
    # "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
    # "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
    # "~/.config/alacritty/themes/themes/github_dark.toml"
    "~/.config/alacritty/themes/themes/gruvbox_material_hard_dark.toml"
]

# [shell]
# program = "/opt/homebrew/bin/tmux"
